### PR TITLE
Add loading animation

### PR DESCRIPTION
**Pull request by komalahuwalia**
Before your pull request is reviewed and merged, please ensure that:

* [x] there are no linting errors
* [x] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [x] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`
* [ ] **Make sure you have run the tests!!**
  * [x] Integration test & Server unit tests - run `npm run allTest` from the server folder
  * [x] Client unit test - run `npm run test` from client folder
  * [ ] End to End test - run `npm run test` from the root folder

Thank you!

### CODE REVIEW

**Comment by komalahuwalia** [comment]
Yes. That's going to be a different one

**Comment by MathuraMG** [comment]
@komalahuwalia - lets merge this

**Comment by MathuraMG** [comment]
fixes #646

**Comment by MathuraMG** [comment]
@komalahuwalia lets start the animation cycle at the full logo

**Comment by komalahuwalia** [comment]
This loaded is not needed given the generic loader

**Pull request closed without merging**
