### PR TITLE
add storybook

### LINKED ISSUE #844: Add Storybook
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### New feature details:
add [Storybook](https://storybook.js.org/docs/basics/introduction/)

### PR DESCRIPTION
**Pull request by MathuraMG**
Before your pull request is reviewed and merged, please ensure that:

Fixes #844 

* [ ] there are no linting errors
* [x] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [x] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`
* [x] **Make sure you have run the tests!!**
  * [x] Integration test & Server unit tests - run `npm run allTest` from the server folder
  * [x] Client unit test - run `npm run test` from client folder
  * [ ] End to End test - run `npm run test` from the root folder

Thank you!

### CODE REVIEW

**Comment by MathuraMG** [comment]
@komalahuwalia - I am unable to run E2E tests on this - would you mind checking it?

**Comment by komalahuwalia** [comment]
The changes look good. I was able to run `npm run storybook` and start storybook. Shall we enhance the ReadMe with 1. How to start story book 2. How to add a new component to story book. Rest all looks good to me

**Comment by regve** [comment]
@komalahuwalia @MathuraMG I would really appreciate if we could enhance the ReadMe with suggested points. No rush and I can find info online, but once time for it, would also like to have our own reference point for it.

**Comment by MathuraMG** [comment]
@komalahuwalia -could you have a look?
@reginavetka  - sorry,  didn't realize I didn't push the README at all.

**Comment by MathuraMG** [comment]
@komalahuwalia - @reginavetka confirmed that this looks ok. Shall i merge, and deploy it?

**Pull request merged**
