### PR TITLE
Remix unsaved changes bug

### PR DESCRIPTION
**Pull request by komalahuwalia**
Before your pull request is reviewed and merged, please ensure that:

* [x] there are no linting errors
* [x] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [x] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`
* [ ] **Make sure you have run the tests!!**
  * [x] Integration test & Server unit tests - run `npm run allTest` from the server folder
  * [x] Client unit test - run `npm run test` from client folder
  * [x] End to End test - run `npm run test` from the root folder

Thank you!

### CODE REVIEW

**Comment by MathuraMG** [comment]
@komalahuwalia can you please check all the boxes in the PR?

**Comment by komalahuwalia** [comment]
Tests failing:
p5 test Cmd+E shortcut
html code runs and stops
front end code runs and stops
default processing sketch runs and stops
able to embed codepen link
able to embed scratch link
duplicate pebl in the file menu
workspace p5 code runs and stops

**Comment by komalahuwalia** [comment]
This PR refactors Remix / Save code and brings back the code that correctly identifies whether user has unsaved changes on page or not.
If the user has unsaved changes on page, then an alert would be shown before navigating away.
Else no alert would be shown

**Comment by MathuraMG** [comment]
fixes #837

**Pull request merged**
