### PR TITLE
Check user on delete

### PR DESCRIPTION
**Pull request by komalahuwalia**
Before your pull request is reviewed and merged, please ensure that:

* [ ] there are no linting errors
* [ ] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [ ] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`
* [ ] **Make sure you have run the tests!!**

Thank you!

### CODE REVIEW

**Comment by MathuraMG** [comment]
fixes #676

**Comment by MathuraMG** [comment]
@komalahuwalia could we add the same check for duplicate? i.e - make sure that a user owns the page before duplicating it?

**Comment by komalahuwalia** [comment]
> @komalahuwalia could we add the same check for duplicate? i.e - make sure that a user owns the page before duplicating it?

The duplicate page calls '/pages/save' url which is a generic url. There is no way for us to know this on the server side. This check might make sense on the client side, but it isn't possible on the server side

**Comment by MathuraMG** [comment]
@komalahuwalia  Is this in staging?

**Comment by komalahuwalia** [comment]
> lets put this in staging!

Deployed!

**Pull request merged**
