### PR TITLE
Save Question height

### LINKED ISSUE #181: the height of the question textbox isnt saved
When you open a doc that has a long question most of the question is obscured

### PR DESCRIPTION
**Pull request by MathuraMG**
fixes #181

### CODE REVIEW

**Comment by estherhersh** [comment]
screen shot 2018-04-23 at 4 53 14 pm
It shows up like this when you add a question

**Comment by estherhersh** [comment]
Ideally, for both questions and answers and text boxes, the div would just increase to fit the content. The scrollbars behave kind of strangely and there's no need for them but until we have a solution for that I think just increasing the default height would be fine. It's saving the height now which is great. I'm also not sure why the bottom line of the answer box disappeared

**Comment by MathuraMG** [comment]
So, both of them increasing automatically works weirdly, let me show you tomo?
And yes, I'll add that back, I forgot to fix that

**Comment by MathuraMG** [comment]
@estherhersh  could you review this?

**Comment by estherhersh** [comment]
can we make the inner height 30 instead? and keep that as the min height when you're dragging as well?

**Comment by MathuraMG** [comment]
Yes, Ill change it to 30. Im genuinely confused why it doesn't stay at 30 though.. it becomes 50..

**Comment by MathuraMG** [comment]
@estherhersh  - you mind checking this once more?

**Comment by estherhersh** [comment]
It looks good! we can deal with the min height thing later... maybe let's make that a diff issue and merge for now?

**Comment by MathuraMG** [comment]
@estherhersh- but the min height does work now, it's 30 across the board . I just wanted to add what the issue was :)

**Pull request merged**
